### ISSUE TITLE
Add a readme file

### ISSUE THREAD

**Issue by ExcaliburZero** [christian-marie/phone-numbers#2]
Currently it is not easy to find information about the library via its GitHub repo. This could be helped by adding a readme file with some basic information on what the library is and how to use it.

**Comment by christian-marie** [comment]
Agreed, thanks. Will do.

**Comment by jberryman** [comment]
This can be closed.

**Comment by christian-marie** [comment]
@jberryman thanks.

P.S. happy to add you as a maintainer if you are going to be using this. @mwotton this goes for you also.
